V3.1.0 acquia send method arguments syntax fix
acquia/aws-flow-ruby pull request #18
Opened 2023-10-12 16:13 UTC by haseeb-ahmad

**Motivation**
Wrong number of params in cluster.rb
Fixes for #CPD-8052

**Proposed changes**

**Alternatives considered**

**Testing steps**

2023-11-27 13:07 UTC, stephenthedev approved these changes

2023-11-29 04:41 UTC, kaushik requested changes
The above suggestion might mean that some of the activity changes might not be needed in the worker PR

2023-11-29 04:41 UTC, kaushik commented on aws-flow/lib/aws/decider/generic_client.rb
> +      def send_async(task, **args, &block)
This looks like it is taking away the functionality for positional arguments for keyword args.

2023-11-29 04:41 UTC, kaushik commented on aws-flow/lib/aws/decider/generic_client.rb
> +      def send_async(task, **args, &block)
If one splat is used it splits the positional arguments from an array into individual arguments.
But in ruby 3 keyword arguments are treated separately from positional arguments. so *args would not contain keyword arguments that are passed to it. You change allows it to accept keyword arguments but not positional arguments.

2023-11-29 04:41 UTC, kaushik commented on aws-flow/lib/aws/decider/generic_client.rb
> +      def send_async(task, **args, &block)
I played around with it in pry
```
def async(task, *args, **kwargs)
  send(task, *args, **kwargs)
end
[29] pry(main)> def met3(a, b:)
  p a+b
=> :met3
[33] pry(main)> async(:met3, 2, b: 3)
5
=> 5
```
As you can see I am able to accept and pass both positional and keyword arguments. This worked on both ruby 2.7 and 3.1.2

2023-12-01 14:33 UTC, kaushik approved these changes

2023-12-01 14:38 UTC, kaushik requested changes

2023-12-01 14:38 UTC, kaushik commented on aws-flow/Gemfile.lock
> +GIT
I don't believe the lock file is part of this repo. Is there a reason you added it now?

2023-12-01 14:59 UTC, kaushik approved these changes

2023-12-08 15:10 UTC, merged